// Liberation Builder Helper - Component Macros
#define COMPONENT main
#define COMPONENT_BEAUTIFIED Liberation Builder Helper

#define PREFIX LBH
#define MAJOR 0
#define MINOR 2
#define PATCH 1
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCH.BUILD
#define VERSION_STR "0.2.1.0"
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD

// Macro for function name
#define FUNC(var1) PREFIX##_fnc_##var1
#define QFUNC(var1) QUOTE(FUNC(var1))

// Quote macro
#define QUOTE(var1) #var1
#define DOUBLES(var1,var2) var1##_##var2

// Dialog IDDs
#define IDD_MAIN_PANEL 58001
#define IDD_COST_DIALOG 58002
#define IDD_CATEGORY_SELECT 58003
#define IDD_EXPORT_WIZARD 58004
#define IDD_TEXT_INPUT 58005

// Control IDCs
#define IDC_PRESET_COMBO 1001
#define IDC_CATEGORY_COMBO 1002
#define IDC_CLASSNAME_LIST 1003
#define IDC_SEARCH_EDIT 1004
#define IDC_BTN_ADD 1005
#define IDC_BTN_REMOVE 1006
#define IDC_BTN_EXPORT 1007
#define IDC_BTN_CLEAR 1008
#define IDC_BTN_CLOSE 1009
#define IDC_STATUS_TEXT 1010

// Cost dialog controls
#define IDC_COST_SUPPLIES 2001
#define IDC_COST_AMMO 2002
#define IDC_COST_FUEL 2003
#define IDC_COST_OK 2004
#define IDC_COST_CANCEL 2005
#define IDC_COST_CLASSNAME 2006

// Category select controls
#define IDC_CATSEL_LIST 3001
#define IDC_CATSEL_OK 3002
#define IDC_CATSEL_CANCEL 3003

// Export Wizard controls
#define IDC_WIZARD_PATH 5801
#define IDC_WIZARD_BROWSE 5802
#define IDC_WIZARD_RECENT 5803
#define IDC_WIZARD_STATUS 5804
#define IDC_WIZARD_CLOSE 5805
#define IDC_WIZARD_COPY_BLUFOR 5810
#define IDC_WIZARD_COPY_OPFOR 5811
#define IDC_WIZARD_COPY_RESISTANCE 5812
#define IDC_WIZARD_COPY_CIVILIANS 5813
#define IDC_WIZARD_COPY_ARSENAL 5814
#define IDC_WIZARD_OPEN_BLUFOR 5820
#define IDC_WIZARD_OPEN_OPFOR 5821
#define IDC_WIZARD_OPEN_RESISTANCE 5822
#define IDC_WIZARD_OPEN_CIVILIANS 5823
#define IDC_WIZARD_OPEN_ARSENAL 5824
#define IDC_WIZARD_COUNT_BLUFOR 5830
#define IDC_WIZARD_COUNT_OPFOR 5831
#define IDC_WIZARD_COUNT_RESISTANCE 5832
#define IDC_WIZARD_COUNT_CIVILIANS 5833
#define IDC_WIZARD_COUNT_ARSENAL 5834

// Text Input Dialog controls
#define IDC_TEXT_INPUT_LABEL 6001
#define IDC_TEXT_INPUT_EDIT 6002
#define IDC_TEXT_INPUT_OK 6003
#define IDC_TEXT_INPUT_CANCEL 6004
