/*
 * Function: LBH_fnc_exportPresetToClipboard
 * Description: Export a single preset to clipboard as a complete custom.sqf file
 *
 * Arguments:
 *   0: STRING - Preset name ("blufor", "opfor", "resistance", "civilians", "arsenal")
 *
 * Return Value:
 *   BOOLEAN - True if successful
 *
 * Example:
 *   ["blufor"] call LBH_fnc_exportPresetToClipboard;
 */

#include "..\script_component.hpp"

params [["_preset", "", [""]]];

if (_preset == "") exitWith {
    ["No preset specified!", 1, 3] call LBH_fnc_showNotification;
    false
};

private _presetData = LBH_data getOrDefault [_preset, createHashMap];
private _categories = LBH_categories getOrDefault [_preset, []];

// Get current date for header
private _dateArr = systemTime;
private _dateStr = format ["%1-%2-%3", _dateArr select 0, _dateArr select 1, _dateArr select 2];

private _output = [];

// Generate file header based on preset type
private _presetHeader = switch (_preset) do {
    case "blufor": {
        [
            "/*",
            "    Specific logic for this faction",
            "",
            "    This file is used for defining the various prices of objects that are spawned through the build menu.",
            "",
            "    BLUFOR Custom Preset",
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
    case "opfor": {
        [
            "/*",
            "    Specific logic for this faction",
            "",
            "    This file is used for setting unit classnames and various other settings like vehicles, etc.",
            "",
            "    OPFOR Custom Preset",
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
    case "resistance": {
        [
            "/*",
            "    Specific configuration for resistance/guerrilla units",
            "",
            "    Resistance Custom Preset",
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
    case "civilians": {
        [
            "/*",
            "    Specific configuration for civilians",
            "",
            "    Civilians Custom Preset",
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
    case "arsenal": {
        [
            "/*",
            "    Arsenal custom preset",
            "",
            "    This file contains the list of all items available in the Arsenal.",
            "",
            "    Arsenal Custom Preset",
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
    default {
        [
            "/*",
            format ["    %1 Custom Preset", toUpper _preset],
            format ["    Generated by Liberation Builder Helper - %1", _dateStr],
            "*/",
            ""
        ]
    };
};

_output append _presetHeader;

// Single value variables first
private _singleVars = _categories select {(_x select 2) isEqualTo "single"};
if (count _singleVars > 0) then {
    _output pushBack "// Unit classnames";
    {
        _x params ["_key", "_displayName", "_format"];
        private _value = _presetData getOrDefault [_key, ""];
        // Always include single values, even if empty
        _output pushBack format ["%1 = ""%2"";", _key, _value];
    } forEach _singleVars;
    _output pushBack "";
};

// Cost format arrays (BLUFOR buildable items)
private _costArrays = _categories select {(_x select 2) isEqualTo "cost"};
if (count _costArrays > 0) then {
    {
        _x params ["_key", "_displayName", "_format"];
        private _items = _presetData getOrDefault [_key, []];
        // Always include arrays, even if empty
        _output pushBack format ["// %1", _displayName];
        _output pushBack ([_items, _key] call LBH_fnc_formatCostArray);
        _output pushBack "";
    } forEach _costArrays;
};

// Simple format arrays
private _simpleArrays = _categories select {(_x select 2) isEqualTo "simple"};
if (count _simpleArrays > 0) then {
    {
        _x params ["_key", "_displayName", "_format"];
        private _items = _presetData getOrDefault [_key, []];
        // Always include arrays, even if empty
        _output pushBack format ["// %1", _displayName];
        _output pushBack ([_items, _key] call LBH_fnc_formatSimpleArray);
        _output pushBack "";
    } forEach _simpleArrays;
};

private _result = _output joinString endl;

// Copy to clipboard
copyToClipboard _result;

// Show notification with target file hint
private _targetFile = switch (_preset) do {
    case "blufor": { "presets/blufor/custom.sqf" };
    case "opfor": { "presets/opfor/custom.sqf" };
    case "resistance": { "presets/resistance/custom.sqf" };
    case "civilians": { "presets/civilians/custom.sqf" };
    case "arsenal": { "arsenal_presets/custom.sqf" };
    default { "custom.sqf" };
};

private _lineCount = count _output;
[format ["%1 copied! (%2 lines) - Paste into %3", toUpper _preset, _lineCount, _targetFile], 0, 5] call LBH_fnc_showNotification;

// Also save the path if validation was successful
call LBH_fnc_saveCurrentPathToRecent;

diag_log format ["[LBH] Exported %1 preset to clipboard (%2 lines)", _preset, _lineCount];

true
