/*
 * Function: LBH_fnc_exportPreset
 * Description: Export all presets to clipboard as SQF code
 *
 * Arguments:
 *   0: STRING - Preset to export (optional, empty = all)
 *
 * Return Value:
 *   STRING - Generated SQF code
 *
 * Example:
 *   call LBH_fnc_exportPreset;
 *   "blufor" call LBH_fnc_exportPreset;
 */

#include "..\script_component.hpp"

params [["_targetPreset", "", [""]]];

private _output = [];

// Header
_output pushBack "// ====================================================================";
_output pushBack "// KP Liberation Preset - Generated by Liberation Builder Helper";
_output pushBack format ["// Generated: %1", systemTime apply {str _x} joinString "-"];
_output pushBack "// ====================================================================";
_output pushBack "";

private _presetsToExport = if (_targetPreset != "") then {
    [_targetPreset]
} else {
    LBH_presets
};

{
    private _preset = _x;
    private _presetData = LBH_data getOrDefault [_preset, createHashMap];
    private _categories = LBH_categories getOrDefault [_preset, []];

    // Skip empty presets
    private _hasData = false;
    {
        _x params ["_key", "_displayName", "_format"];
        private _data = _presetData getOrDefault [_key, []];
        if (_format isEqualTo "single") then {
            if (_data isEqualType "" && {_data != ""}) then {
                _hasData = true;
            };
        } else {
            if (count _data > 0) then {
                _hasData = true;
            };
        };
    } forEach _categories;

    if (!_hasData) then {
        continue;
    };

    // Preset header
    private _presetHeader = switch (_preset) do {
        case "blufor": { "BLUFOR Preset" };
        case "opfor": { "OPFOR Preset" };
        case "resistance": { "Resistance Preset" };
        case "civilians": { "Civilians Preset" };
        case "arsenal": { "Arsenal Preset" };
        default { _preset };
    };

    _output pushBack format ["// --------------------------------------------------------------------"];
    _output pushBack format ["// %1", _presetHeader];
    _output pushBack format ["// --------------------------------------------------------------------"];
    _output pushBack "";

    // Single value variables first
    private _singleVars = _categories select {(_x select 2) isEqualTo "single"};
    if (count _singleVars > 0) then {
        _output pushBack "// Single value classnames";
        {
            _x params ["_key", "_displayName", "_format"];
            private _value = _presetData getOrDefault [_key, ""];
            if (_value != "") then {
                _output pushBack format ["%1 = ""%2"";", _key, _value];
            };
        } forEach _singleVars;
        _output pushBack "";
    };

    // Cost format arrays
    private _costArrays = _categories select {(_x select 2) isEqualTo "cost"};
    if (count _costArrays > 0) then {
        {
            _x params ["_key", "_displayName", "_format"];
            private _items = _presetData getOrDefault [_key, []];
            if (count _items > 0) then {
                _output pushBack format ["// %1", _displayName];
                _output pushBack ([_items, _key] call LBH_fnc_formatCostArray);
                _output pushBack "";
            };
        } forEach _costArrays;
    };

    // Simple format arrays
    private _simpleArrays = _categories select {(_x select 2) isEqualTo "simple"};
    if (count _simpleArrays > 0) then {
        {
            _x params ["_key", "_displayName", "_format"];
            private _items = _presetData getOrDefault [_key, []];
            if (count _items > 0) then {
                _output pushBack format ["// %1", _displayName];
                _output pushBack ([_items, _key] call LBH_fnc_formatSimpleArray);
                _output pushBack "";
            };
        } forEach _simpleArrays;
    };
} forEach _presetsToExport;

// Footer
_output pushBack "// ====================================================================";
_output pushBack "// End of preset file";
_output pushBack "// ====================================================================";

private _result = _output joinString endl;

// Copy to clipboard
copyToClipboard _result;

// Show notification
private _lineCount = count _output;
[format ["Exported %1 lines to clipboard!", _lineCount], 0, 3] call LBH_fnc_showNotification;

diag_log format ["[LBH] Exported preset(s): %1 (%2 lines)", _presetsToExport, _lineCount];

_result
